name: Cleanup Action Logs

on:
  # schedule:
  #   - cron: '0 16 * * *'
  workflow_dispatch: 

permissions:
  actions: write
  contents: read

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "正在开始清理所有历史记录"
          run_ids=$(gh api "repos/${{ github.repository }}/actions/runs?per_page=100" \
            --jq '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | .id')

          if [ -z "$run_ids" ]; then
            echo "未发现需要清理的日志。"
            exit 0
          fi

          for run_id in $run_ids; do
            run_info=$(gh api "repos/${{ github.repository }}/actions/runs/$run_id" --jq '.name')
            echo "正在清理日志: $run_info ID: $run_id"
            gh api -X DELETE "repos/${{ github.repository }}/actions/runs/$run_id" --silent
          done
          
          echo "清理完成！"
